### ISSUE TITLE
Is there a way to run it inside raspbian?

### ISSUE THREAD

**Issue by hummuscience** [guysoft/ElectricSheepPi#2]
I tried building it from withing Raspbian but I always end up with a "no space left" error even thought it is a clean raspbian install on a 8Gb SD-Card.

I also expanded the file system before I ran the script.

Any idea what is happening?

**Comment by guysoft** [comment]
You can attach an external device and format it to ext4. Then you will have enough space.
You do understand that this builds an image you need to flash afterwards, right?
Why are you building it?

**Comment by guysoft** [comment]
Building method is not CustomPiOS based, you can build it from rasbian using the docker image since version 1.3.0
