### ISSUE TITLE
Root Login information?

### ISSUE THREAD

**Issue by FakeyMcFakeFake** [guysoft/ElectricSheepPi#3]
I have LOTS of sheep files on my other computer I would like to just copy onto the Pi. I'm having trouble logging in. What is the root password? Or is there another way into the OS?

Thank you.
AS

**Comment by guysoft** [comment]
As written in [step 5 in the readme](https://github.com/guysoft/ElectricSheepPi/blob/master/README.rst#how-to-use-it) its the same as raspbian default,  which is user ``pi`` and password ``raspberry``. Root is accessible using ``sudo``.
