### ISSUE TITLE
Permission to use electricsheep logo for rpi-imager entry

### ISSUE THREAD

**Issue by guysoft** [guysoft/ElectricSheepPi#7]
Hey,
I want to add an rpi-imager entry. similar to other distributions I maintain.

@scottdraves May I use the electricsheep logo for the icon entry?

It also raises the chance it would be accepted to the official rpi-imager.
Reguardless it will go to my community maintained pi-imager: https://github.com/guysoft/pi-imager

This is how it will look:
![Screenshot_20220321_010730](https://user-images.githubusercontent.com/325670/159189994-71d0b96d-5b83-4272-a64c-e3a2d4a59c40.png)

This is how it looks now in the current nightly build, planned to be released after this issue is resolved:
![Screenshot_20220321_005832](https://user-images.githubusercontent.com/325670/159189733-5e56b8fd-9990-40bb-a7e7-73a68aa8ba4f.png)

**Comment by scottdraves** [comment]
yes please! thanks for asking.

**Comment by guysoft** [comment]
Thanks! Done.
